"""add crypto symbols

Revision ID: 60bb002f17e4
Revises: 7b761ff71a3f
Create Date: 2026-01-20 13:47:45.909142

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '60bb002f17e4'
down_revision = '7b761ff71a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('coingecko_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_crypto_symbols_symbol')
    )
    op.create_index(op.f('ix_crypto_symbols_coingecko_id'), 'crypto_symbols', ['coingecko_id'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_symbol'), 'crypto_symbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_symbols_symbol'), table_name='crypto_symbols')
    op.drop_index(op.f('ix_crypto_symbols_coingecko_id'), table_name='crypto_symbols')
    op.drop_table('crypto_symbols')
    # ### end Alembic commands ###
